package com.esprit;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-05-10T02:40:18.680+01:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "EtudiantServiceService", 
                  wsdlLocation = "http://192.168.0.102:8383/smartClass/EtudiantService?wsdl",
                  targetNamespace = "http://service.esprit.com/") 
public class EtudiantServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.esprit.com/", "EtudiantServiceService");
    public final static QName EtudiantServicePort = new QName("http://service.esprit.com/", "EtudiantServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.102:8383/smartClass/EtudiantService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EtudiantServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.102:8383/smartClass/EtudiantService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EtudiantServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EtudiantServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EtudiantServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EtudiantServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EtudiantServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EtudiantServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns EtudiantService
     */
    @WebEndpoint(name = "EtudiantServicePort")
    public EtudiantService getEtudiantServicePort() {
        return super.getPort(EtudiantServicePort, EtudiantService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EtudiantService
     */
    @WebEndpoint(name = "EtudiantServicePort")
    public EtudiantService getEtudiantServicePort(WebServiceFeature... features) {
        return super.getPort(EtudiantServicePort, EtudiantService.class, features);
    }

}
